// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAkC8qIcpkpznfx7-PEKBPJ8b3ix7MXzg',
    appId: '1:640686739098:web:409d01578610c0d5b49923',
    messagingSenderId: '640686739098',
    projectId: 'olimpiada-384506',
    authDomain: 'olimpiada-384506.firebaseapp.com',
    storageBucket: 'olimpiada-384506.appspot.com',
    measurementId: 'G-M7FG6BC5RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEyKW46wRErFKJd-veMOx2OZcuvoV85mg',
    appId: '1:640686739098:android:09d97a9260b57d83b49923',
    messagingSenderId: '640686739098',
    projectId: 'olimpiada-384506',
    storageBucket: 'olimpiada-384506.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd1sL6zlQN8Et81T17bu1k1fnR5g_fr0g',
    appId: '1:640686739098:ios:46147882d8277b99b49923',
    messagingSenderId: '640686739098',
    projectId: 'olimpiada-384506',
    storageBucket: 'olimpiada-384506.appspot.com',
    iosClientId: '640686739098-emqasdds3bg3ik4deij66k76nfst9rg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.concurs',
  );
}
